baseURL = "http://blog.laro.dev/"
languageCode = "en-us"
title = "Laro dev - blog"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true

[params]
  copyright = "Copyright © 2022 - Laro dev"
  dark = "auto"
  highlight = true
  mainSections = ['posts']
  
[taxonomies]
  tag = 'tags'

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    pre = "/ "
    post = " /"
    weight = 10
  [[menu.main]]
    identifier = "rss"
    name = "rss"
    title = "rss"
    url = "/index.xml"
    weight = 20
    post = " /"

[permalinks]
  posts = "/posts/:filename/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.tableOfContents]
  ordered = true